# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNIOSShell' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNIOSShell

  # 如果你的RN版本 >= 0.42.0，则加入下面这行


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end

